[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "2c6523ce162ec3ce2e9439f6bcc9b019e53fb93a"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "98cf5e2356c3984d092b77fd2fda2a83514d4e3ec83e6b69aa87d4c9df065a80"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "429d81cd25c808c4f937e82beb7c40bff6fc7ae2"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "c274d5b36bc62bd1c1eae597a1793390015a0d5904257d801d88d4e8d95e8cce"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "aa2c7332364c6b5495e1d894335d6407d9e6fef9"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "2a970f626279bd421d7a189b94aac7583fbfa5f11a9350fdafb8b17e5e72c320"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2353aac1c65177b398cb01ebd0c234a565327bd5"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "627e021c8f5c7f0e9210809f37d7671b13817d19b9d2dec842dac7eb099c6e05"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e26c12879358a32437be61e52dc38d50f8fdd64"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "88df35b92992cebc2ac21af01e2e2a39cf5581c4377d297b23973d168954d813"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a45593df1c1d6a0fac2627a34cca282a3da8d2b"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "8c0f1fdfb8d047e46d73559a26685f3e4d5f398705e648d771b16c1e04791da8"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "ed3d71f7171aaf4ae5b321eafd57f3ec6cb7ae40"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "2565be70a4f32f6eca8d6671900a4baf5c0bb2e6a522d20337117f0569a3d15d"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "a27bcdb98af8fe0dfdfa3ab1dd93b43d67bf24a1"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "3264c94490c40207b8afa72d40fb8704ffd2c6563c392477a99e01ec0f7e3741"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "75d1b8331af8b6b72c0f2c60f8fbc9acce33cfd0"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "ab5c4cc13225eb391e617768f4c590ca13690d16f2e626050473892c9086c391"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "952ccf055d07e679dafaa087f49aa0ec8215ae10"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "e7f8b3db814266e174c5f09f293deaf7e3fe26238d674b6f73dfeaaaf2fc53de"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6654661daf4f8c964dedf0b3838afddd4e5e3f39"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "23ae40351df898498a32c29dcea0535db3c381c75286f061b9a9499d4db8aa9e"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29142129b702b39abca63eb38648eb6c38694cae"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "4f320544b4b44c99774df130e24a3df5bad4d3e42e7d748bed891ff637a87529"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "3c16eaccf88d44ad620941acd3e10a3897916ed4"
julia_version = "1.10.0"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "81cf06369e0812703cd9da123b653db007bbaf460bd8a91a4920290e95423fcd"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "8060f172bf201b3a046c975405abfb38f4753f4a"
julia_version = "1.11.1"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "03e92ab14ef23406baeabbf926ee0ff517e40f2e2149a970c0ed3cf63a517862"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "92859ee3463675b90ac32dffd7058abdc886258f"
julia_version = "1.12.0"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "2fcde6a259913e122709451c1868f6d8c2a7338bff680a7838212ca4afdef9f2"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "362ce6487add829bb28fe269593e97fb06df3b4e"
julia_version = "1.10.0"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "c61afbf4cb11722029f82269eb895a5c588173081dd074616d83122f2fc51ade"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f7992d9f3474e1831b0cfd49c285dc1ddb0ef07"
julia_version = "1.11.1"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "f9e91c8e3b223a7d2c8c93b6ebd45060530b25c09e3d8e2f06ac2f0cf04da3f6"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06af245432b3205a805c7785fad317ca59d6b03e"
julia_version = "1.12.0"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "3df5c706098bda69d9d7a25b1084107d8868048254a883758d1b6bd6ba9beeb7"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.6.0+0/openfhe_julia_int128.v0.6.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
